### ISSUE TITLE
Thrift crashes if Postgres instance isn't ready in time

### ISSUE THREAD

**Issue by dmateusp** [godatadriven-dockerhub/spark#1]
The dependency in docker-compose:
```
    depends_on:
      - hive-metastore
```

is sometimes not enough to guard against the database not being ready when the Thrift server attempts to start

I would suggest changing the entrypoint to include some retry mechanism like:

https://github.com/fishtown-analytics/dbt-spark/pull/58/files#diff-aff5cb8cae7e6f2b56f2f043c71cfd10R8

Here's the issue I run into:

```
thrift_1          | Caused by: java.net.ConnectException: Connection refused (Connection refused)
thrift_1          | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
thrift_1          | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
thrift_1          | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
thrift_1          | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
thrift_1          | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
thrift_1          | 	at java.net.Socket.connect(Socket.java:607)
thrift_1          | 	at org.postgresql.core.PGStream.<init>(PGStream.java:70)
thrift_1          | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
thrift_1          | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
thrift_1          | 	... 93 more
thrift_1          | 20/03/14 18:39:35 INFO SparkContext: Invoking stop() from shutdown hook
thrift_1          | 20/03/14 18:39:35 INFO SparkUI: Stopped Spark web UI at http://3d85c2e331f6:4040
thrift_1          | 20/03/14 18:39:35 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
thrift_1          | 20/03/14 18:39:35 INFO MemoryStore: MemoryStore cleared
thrift_1          | 20/03/14 18:39:35 INFO BlockManager: BlockManager stopped
thrift_1          | 20/03/14 18:39:35 INFO BlockManagerMaster: BlockManagerMaster stopped
thrift_1          | 20/03/14 18:39:35 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
thrift_1          | 20/03/14 18:39:35 INFO SparkContext: Successfully stopped SparkContext
thrift_1          | 20/03/14 18:39:35 INFO ShutdownHookManager: Shutdown hook called
thrift_1          | 20/03/14 18:39:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-c4b03e86-93b9-4726-802f-8ade21a8278d
thrift_1          | 20/03/14 18:39:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-be1b59d6-ea24-4101-8ef4-b1e4c1c164cc
dbt-spark_thrift_1 exited with code 1
```

Note that it doesn't always happen

**Comment by NielsZeilemaker** [comment]
I'll add a custom entrypoint to wait for the thrift server.

**Comment by NielsZeilemaker** [comment]
@dmateusp done, dockerhub is building, the images should be updated in half an hour
